WP-112 Implement dark mode
ericgmoon/wybo pull request #85
Opened 2022-08-18 23:30 UTC by ericgmoon

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/32473932/185512044-1a5fbba2-84f7-4583-aed3-940429640282.png">
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/32473932/185512088-2559a2e8-03fe-4e02-8737-cd8458f7b7cf.png">
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/32473932/185512115-7e6c77d7-73ee-4f49-90c2-e8e34d7b5b20.png">
<img width="562" alt="image" src="https://user-images.githubusercontent.com/32473932/185512241-b3e42bf7-4f76-44aa-835c-09422a77c2a0.png">
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/32473932/185512240-b4c9f792-a53c-4e81-b4b0-b47d58b9d1fe.png">

2022-08-18 23:52 UTC, ericgmoon commented
Update: restyled drawer nav
<img width="317" alt="image" src="https://user-images.githubusercontent.com/32473932/185514332-b6521ad3-e07f-4eb7-b237-5cbb12a4f250.png">

2022-08-19 07:00 UTC, s-hane requested changes
Should be more dynamically applied rather than manual for each component

2022-08-19 08:22 UTC, ericgmoon commented on src/components/PageLayout/AppBar/index.styles.ts
> +    background-color: ${({ theme }) => (isDark(theme) ? theme.palette.backdrop.main : theme.palette.darkPrimary.main)};
This is the only place that requires manual adjustment. I couldn't find a nice way to make this part dynamic without compromising style. I think this should be the only place where this is necessary - the `AppBar` is such a large piece of the screen estate that I didn't want to compromise on design

2022-08-19 08:30 UTC, ericgmoon commented
<img width="1498" alt="image" src="https://user-images.githubusercontent.com/32473932/185578282-608623fe-a60f-4ea3-adca-ce1411dfa773.png">
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/32473932/185578315-8a97ddc5-239f-4efd-8841-e79614abb950.png">

2022-08-19 08:42 UTC, s-hane approved these changes

2022-08-19 08:43 UTC, merged